// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmSQpglfZpdnm7UELudXs4lP9OAjwAME',
    appId: '1:1012024979698:web:24446da68cbe09fc8ce06b',
    messagingSenderId: '1012024979698',
    projectId: 'organizador-80a7d',
    authDomain: 'organizador-80a7d.firebaseapp.com',
    storageBucket: 'organizador-80a7d.firebasestorage.app',
    measurementId: 'G-CGHW64KTM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhCS7YpXCAUAQYURcAlCUE8PaJaST4mE',
    appId: '1:1012024979698:android:84028c2dac3af4a08ce06b',
    messagingSenderId: '1012024979698',
    projectId: 'organizador-80a7d',
    storageBucket: 'organizador-80a7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2A-Gm_V907lLKseVzZ35vU-CgdjEVnw',
    appId: '1:1012024979698:ios:313074de1f04aeec8ce06b',
    messagingSenderId: '1012024979698',
    projectId: 'organizador-80a7d',
    storageBucket: 'organizador-80a7d.firebasestorage.app',
    iosBundleId: 'com.example.organizador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ2A-Gm_V907lLKseVzZ35vU-CgdjEVnw',
    appId: '1:1012024979698:ios:313074de1f04aeec8ce06b',
    messagingSenderId: '1012024979698',
    projectId: 'organizador-80a7d',
    storageBucket: 'organizador-80a7d.firebasestorage.app',
    iosBundleId: 'com.example.organizador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmSQpglfZpdnm7UELudXs4lP9OAjwAME',
    appId: '1:1012024979698:web:8306c89fef9aea7a8ce06b',
    messagingSenderId: '1012024979698',
    projectId: 'organizador-80a7d',
    authDomain: 'organizador-80a7d.firebaseapp.com',
    storageBucket: 'organizador-80a7d.firebasestorage.app',
    measurementId: 'G-1BNE8F6EH3',
  );
}
